from ...gg import style

STYLE = style.GGSTYLE

PLAYER_NAME = "Player"
ENEMY_NAME = "Enemy"
WALL_NAME = "Wall"

PLAYER_COLOR = STYLE.WHITE
ENEMY_COLOR = STYLE.RED
WALL_COLOR = STYLE.BROWN
DEATH_COLOR = STYLE.BLACK
