from ...gg import style
from typing import NamedTuple

STYLE = style.GGSTYLE

PLAYER_NAME = "Player"
BULLET_NAME = "Bullet"
ENEMY_NAME = "Enemy"
WALL_NAME = "Wall"

PLAYER_COLOR = STYLE.NEON_BLUE
BULLET_COLOR = STYLE.NEON_BLUE
ENEMY_COLOR = STYLE.RED
WALL_COLOR = STYLE.STONE
DEATH_COLOR = STYLE.BLACK

ALL_TYPE = 0
BULLET_TYPE = 1
PLAYER_TYPE = 2
ENEMY_TYPE = 4
WALL_TYPE = 8